### ISSUE TITLE
uniform_int_distribution i64 minstd_rand generates outside range

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/cpprandom#2]
`uniform_int_distribution i64 minstd_rand` generates numbers outside the range when the range is between negative numbers.
```
import "lib/github.com/diku-dk/cpprandom/random"
module dist = uniform_int_distribution i64 minstd_rand
let snd (_,b) = b
let main = snd <| dist.rand (-20,-10) (minstd_rand.rng_from_seed [1234])
```
This program returns `4294967281i64`, for example

**Comment by athas** [comment]
I think this is because `minstd_rand` produces only (unsigned) 32-bit numbers.

**Comment by athas** [comment]
I think the notion of being able to combine arbitrary RNGs and distributions, regardless of the base type, is fundamentally flawed.  Caveat emptor.  It is unfortunate that we cannot enforce that the size of the generator must match the size of the distribution.
